# Generated by Django 4.2 on 2023-07-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_comment',
            name='comment_id',
        ),
        migrations.RemoveField(
            model_name='vote_comment',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='down_votes',
            new_name='total_votes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='review',
            name='votes',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote_review',
            name='is_positive',
            field=models.SmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.DeleteModel(
            name='Vote_Comment',
        ),
    ]
