# Generated by Django 4.2 on 2023-06-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0002_alter_concert_artist_alter_concert_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
